spring:
  application:
    name: authorization
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_app
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  private-key: classpath:private.key
  public-key: classpath:public.key
  access-token-expiration: 30 # minutes
  refresh-token-expiration: 1440 # minutes = 1 day

app:
  cors: http://localhost:3000,http://0.0.0.0:3000
